# --- CORE ---
spring.application.name=VocabMitra
spring.security.enabled=true
server.port=8080

# --- DATABASE ---
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
# Turned off SQL logging for production to save server memory and keep logs clean
spring.jpa.show-sql=false

# --- SECRETS & PAYMENTS ---
jwt.secret=${JWT_SECRET}
#razorpay.key.id=${RAZORPAY_KEY_ID}
#razorpay.key.secret=${RAZORPAY_KEY_SECRET}


# --- MAIL ---
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#----frontend url's----
dev.frontend.url=${DEV_FRONTEND_URL}
dev.forgot.password.frontend.url=${DEV_FRONTEND_PASSWORD_FORM}
dev.frontend.admin.url=${DEV_FRONTEND_ADMIN_URL}
frontend.url=${FRONTEND_BASE_URL}
forgot.password.frontend.url=${FRONTEND_RESET_PASSWORD_FORM}
frontend.admin.url=${FRONTEND_ADMIN_URL}

# --- LAYER 1: The Database Gatekeeper ---
# Cap the connections at 10. This uses ~150MB of RAM, leaving 850MB for Postgres to actually process the queries.
spring.datasource.hikari.maximum-pool-size=10
# If all 10 are busy, make users wait up to 30 seconds before throwing a 500 error.
spring.datasource.hikari.connection-timeout=30000

# --- LAYER 2: The Tomcat Web Server ---
# Allow 25 active threads. 10 will talk to the DB, the other 15 will wait in line or do non-DB tasks (like Razorpay API calls).
server.tomcat.threads.max=25
# Create a waiting room for 50 extra users.
server.tomcat.accept-count=50